# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "mcvl"
    path: "./bin"
    arch: "amd64"
    system: "linux,windows"
    packSrc: "resource/public,resource/template"
    version: ""
    extra: "-ldflags=\"-s -w\""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app